<a href="https://colab.research.google.com/github/Vanshika-goyal1/AI-Lab/blob/main/Ass1_ai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name :- Vanshika Goyal

Roll Number :- 102215194

Lab Assignment - 1

1. Given two lists—one containing keys and the other containing values.
Create a dictionary by pairing corresponding elements from both lists.

In [ ]:
keys = ['a','b','c']
values = [1,2,3]
dictionary = dict(zip(keys,values))   # zip(keys, values): This pairs each element from the keys list with the corresponding element from the values list, forming tuples like ('a', 1), ('b', 2), and ('c', 3)
print("The created dictionary is: ", dictionary)   # dict(): Converts the list of tuples created by zip into a dictionary,

The created dictionary is:  {'a': 1, 'b': 2, 'c': 3}


2. Write a program that compares two numbers and prints whether they
are equal, not equal, greater than, or less than each other.

In [ ]:
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))

if num1 == num2:
  print("The numbers are equal")
elif num1 > num2:
  print("The first number is greater")
else:
  print("The first number is less")

Enter the first number: 3.2
Enter the second number: 3.5
The first number is less


3. Create a list of length 10 of your choice containing multiple types of
data. Using for loop print the element and its data type.

In [ ]:
my_list = [42,"hello",3.14,True,None,[1,2,3],{'key':'Value'},(5,6),8.9,b'byte']
for i in range(len(my_list)):
  print(f"Element: {my_list[i]}, Type: {type(my_list[i])}")  # f-string format

  # Using string concatenation instead of f-string
  # print("Element: " + str(my_list[i]) + ", Type: " + str(type(my_list[i])))

Element: 42, Type: <class 'int'>
Element: hello, Type: <class 'str'>
Element: 3.14, Type: <class 'float'>
Element: True, Type: <class 'bool'>
Element: None, Type: <class 'NoneType'>
Element: [1, 2, 3], Type: <class 'list'>
Element: {'key': 'Value'}, Type: <class 'dict'>
Element: (5, 6), Type: <class 'tuple'>
Element: 8.9, Type: <class 'float'>
Element: b'byte', Type: <class 'bytes'>


4. Using a while loop, verify if the number A is purely divisible by number
B and if so then how many times it can be divisible.

In [ ]:
# Input numbers A and B
A = int(input("Enter number A: "))
B = int(input("Enter number B: "))

# Ensure B is not zero to avoid division by zero error
if B == 0:
    print("Division by zero is not allowed.")
else:
    # Initialize counters
    count = 0
    original_A = A  # Store the original value of A for reference

    # Calculate the total number of times A can be divided by B
    total_divisions = original_A // B

    # Use a while loop to check divisibility in sequence
    while A % B == 0:
        A //= B  # Divide A by B and update A
        count += 1  # Increment the count

    # Output the results
    if count > 0:
        print(f"Number {original_A} can be divided by number {B} {count} times in sequence.")
    else:
        print(f"Number {original_A} is not divisible by number {B}.")

    print(f"Number {original_A} can be divided by number {B} a total of {total_divisions} times.")

Enter number A: 10
Enter number B: 2
Number 10 can be divided by number 2 1 times in sequence.
Number 10 can be divided by number 2 a total of 5 times.


5. Create a list containing 25 integer type data. Using for loop and if-else
condition print if the element is divisible by 3 or not.

In [ ]:
integer_list = [i for i in range(1,26)] # Create a list containing 25 integer values from 1 to 25

for number in integer_list:   # Loop through each element in the list
  if number % 3 == 0:
    print(f"{number} is divisible by 3.")
  else:
    print(f"{number} is not divisible by 3.")

1 is not divisible by 3.
2 is not divisible by 3.
3 is divisible by 3.
4 is not divisible by 3.
5 is not divisible by 3.
6 is divisible by 3.
7 is not divisible by 3.
8 is not divisible by 3.
9 is divisible by 3.
10 is not divisible by 3.
11 is not divisible by 3.
12 is divisible by 3.
13 is not divisible by 3.
14 is not divisible by 3.
15 is divisible by 3.
16 is not divisible by 3.
17 is not divisible by 3.
18 is divisible by 3.
19 is not divisible by 3.
20 is not divisible by 3.
21 is divisible by 3.
22 is not divisible by 3.
23 is not divisible by 3.
24 is divisible by 3.
25 is not divisible by 3.


**Libraries**

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a,b)

32

In [ ]:
A = np.linspace(1,10,10)
print(A)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
j = np.array([[1, 2, 3],[ 4, 5, 6],[7, 8, 9]])
j[0][1] = 999
j[0][2] = 999
j[1][1] = 999
j[1][2] = 999
print(j)

[[  1 999 999]
 [  4 999 999]
 [  7   8   9]]


In [ ]:
# Coefficient matrix A
A = np.array([[3, 2],
              [10, -1]])

# Constant matrix B
B = np.array([5, 3])

# Inverse of matrix A
A_inv = np.linalg.inv(A)

# Multiplying A_inv with B to get the solution
solution = np.dot(A_inv, B)

print("The solution is:", solution)

The solution is: [0.47826087 1.7826087 ]


In [ ]:
a = np.array([1,2,3,4,5,6])
b = np.array([7,8,9,10,12,17])
mse = np.mean()

3. Generate a 5 by 5 random matrix and find the maximum, minimum,
average (mean) & variance values along all axes.

In [ ]:
import numpy as np
A = np.random.randint(3,10,size=(5,5))
print(A)
A.mean()
A.min()

# b = np.random.randn(5)   # for normalization Gaussian
# b

[[3 3 3 7 4]
 [9 6 9 5 4]
 [9 9 3 6 4]
 [7 4 4 7 3]
 [5 3 3 3 5]]


3

5. Find the mean square error between two array A = [1,2,3,4,5,6] & B =
[7,8,9,10,12,17] using function in Numpy module.

Students based on quality(honesty,Courage,intelligence) converting into numbers :- **feature network matrix**,
**gradient descent**, Importance of mse:- To calculate loss