<a href="https://colab.research.google.com/github/Vanshika-goyal1/AI-Lab/blob/main/Ass2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Libraries**

In [2]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a,b)

32

In [ ]:
A = np.linspace(1,10,10)
print(A)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


1. Generate the following matrix in numpy

A =

1 2 3

4 5 6

7 8 9

and modify the entries to

B =

1 999 999

4 999 999

7  8   9

In [ ]:
j = np.array([[1, 2, 3],[ 4, 5, 6],[7, 8, 9]])
j[0][1] = 999
j[0][2] = 999
j[1][1] = 999
j[1][2] = 999
print(j)

[[  1 999 999]
 [  4 999 999]
 [  7   8   9]]


2.Consider the system of equations

3x + 2y = 5

10x − y = 3

Find the unique solution to these equations using matrix calculus in
Numpy array.

In [ ]:
# Coefficient matrix A
A = np.array([[3, 2],
              [10, -1]])

# Constant matrix B
B = np.array([5, 3])

# Inverse of matrix A
A_inv = np.linalg.inv(A)

# Multiplying A_inv with B to get the solution
solution = np.dot(A_inv, B)

print("The solution is:", solution)

The solution is: [0.47826087 1.7826087 ]


3. Generate a 5 by 5 random matrix and find the maximum, minimum,
average (mean) & variance values along all axes.

In [6]:
import numpy as np
A = np.random.randint(3,10,size=(5,5))
print("Matrix A:")
print(A)

max_value = A.max()
print("Maximum Value:", max_value)

min_value = A.min()
print("Minimum Value:", min_value)

mean_value = A.mean()
print("Mean Value:", mean_value)

variance_value = A.var()
print("Variance Value:", variance_value)

# b = np.random.randn(5)   # for normalization Gaussian
# b

Matrix A:
[[9 4 7 7 6]
 [9 9 8 9 4]
 [5 6 6 7 7]
 [7 5 7 8 6]
 [5 5 4 3 3]]
Maximum Value: 9
Minimum Value: 3
Mean Value: 6.24
Variance Value: 3.3024


4. Generate a 5 by 5 random integer matrix whose values are between 2 & 100. Find the another matrix which produces boolean output as true
where Values of random matrix are between 20 & 70.

In [9]:
random_matrix = np.random.randint(2, 101, size=(5, 5))
boolean_matrix = (random_matrix >= 20) & (random_matrix <= 70)
print("Random Matrix:",)
print(random_matrix)

print("\nBoolean Matrix:",)
print(boolean_matrix)

Random Matrix:
[[25 36 82 60 68]
 [38 61 62  6 90]
 [99 25 70 39 47]
 [ 9  3 18 49 71]
 [70 39 12 87 34]]

Boolean Matrix:
[[ True  True False  True  True]
 [ True  True  True False False]
 [False  True  True  True  True]
 [False False False  True False]
 [ True  True False False  True]]


5. Find the mean square error between two array A = [1,2,3,4,5,6] & B =
[7,8,9,10,12,17] using function in Numpy module.

Students based on quality(honesty,Courage,intelligence) converting into numbers :- **feature network matrix**,
**gradient descent**, Importance of mse:- To calculate loss

In [10]:
a = np.array([1,2,3,4,5,6])
b = np.array([7,8,9,10,12,17])

# Compute squared differences
squared_differences = (a - b) ** 2

# Compute mean of squared differences
mse = np.mean(squared_differences)

print("Mean Squared Error:", mse)

Mean Squared Error: 52.333333333333336


7. Find out the eigen value and eigen vectors of covariance of the data ma-
trix, X=[[4,11],[8,4],[13,5],[7,14]] where each row is one observation while
colums are attribures of that observation. (Hint: Question is related to
PCA & use np.cov and np.linalg.eig functions of numpy package)